#!/usr/bin/env python3
"""Generate the Field Notes index cards and manifest from article metadata.

Every field-notes/*.html article (except index.html) carries its own card
data in <head>:

    <meta name="fn-card-title" content="..." />
    <meta name="fn-card-summary" content="..." />
    <meta name="fn-categories" content="infra performance" />
    <meta name="fn-accent" content="#ea580c" />
    <meta name="fn-published" content="2026-08-26" />

This script reads those tags and:
  1. Rewrites everything between the FN-CARDS markers in
     field-notes/index.html with one card per article.
  2. Writes field-notes/field-notes.json (manifest for later search,
     pagination, category hubs, and related-note links).

Sort order: newest fn-published first, ties broken by slug A-Z.
Valid category keys come from the <scott-filter-bar> JSON block in
field-notes/index.html - that block stays hand-authored.

Exits non-zero (and changes nothing) if any article is missing a tag,
uses an unknown category, or has a malformed accent/date.

Usage:
    python scripts/generate_field_notes.py          # write files
    python scripts/generate_field_notes.py --check  # exit 1 if out of date
"""
import html
import json
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FN_DIR = ROOT / "field-notes"
INDEX = FN_DIR / "index.html"
MANIFEST = FN_DIR / "field-notes.json"
SITE = "https://scottlabz.com"

START = "<!-- FN-CARDS:START - generated by scripts/generate_field_notes.py, do not edit by hand -->"
END = "<!-- FN-CARDS:END -->"

REQUIRED = ("fn-card-title", "fn-card-summary", "fn-categories", "fn-accent", "fn-published")
META_RE = re.compile(r'<meta\s+name="(fn-[a-z-]+)"\s+content="([^"]*)"\s*/?>', re.I)
HEX_RE = re.compile(r"^#[0-9a-f]{6}$")
FILTER_JSON_RE = re.compile(
    r"<scott-filter-bar[^>]*>\s*<script type=\"application/json\">(.*?)</script>", re.S
)


def fail(errors: list[str]) -> None:
    print("generate_field_notes: nothing written, fix these first:", file=sys.stderr)
    for e in errors:
        print(f"  - {e}", file=sys.stderr)
    sys.exit(1)


def valid_categories(index_html: str) -> set[str]:
    m = FILTER_JSON_RE.search(index_html)
    if not m:
        fail(["no <scott-filter-bar> JSON category block found in field-notes/index.html"])
    return {c["key"] for c in json.loads(m.group(1))}


def read_articles(categories: set[str]) -> list[dict]:
    notes, errors = [], []
    for path in sorted(FN_DIR.glob("*.html")):
        if path.name == "index.html":
            continue
        head = path.read_text(encoding="utf-8").split("</head>", 1)[0]
        meta = {k.lower(): html.unescape(v) for k, v in META_RE.findall(head)}
        missing = [k for k in REQUIRED if not meta.get(k, "").strip()]
        if missing:
            errors.append(f"{path.name}: missing {', '.join(missing)}")
            continue
        cats = meta["fn-categories"].split()
        unknown = [c for c in cats if c not in categories]
        if unknown:
            errors.append(f"{path.name}: unknown category {', '.join(unknown)} (valid: {', '.join(sorted(categories))})")
        accent = meta["fn-accent"].strip().lower()
        if not HEX_RE.match(accent):
            errors.append(f"{path.name}: fn-accent must be #rrggbb, got {accent!r}")
        try:
            date.fromisoformat(meta["fn-published"].strip())
        except ValueError:
            errors.append(f"{path.name}: fn-published must be YYYY-MM-DD, got {meta['fn-published']!r}")
        notes.append({
            "slug": path.stem,
            "file": path.name,
            "url": f"{SITE}/field-notes/{path.name}",
            "title": " ".join(meta["fn-card-title"].split()),
            "summary": " ".join(meta["fn-card-summary"].split()),
            "categories": cats,
            "accent": accent,
            "published": meta["fn-published"].strip(),
        })
    if errors:
        fail(errors)
    notes.sort(key=lambda n: n["slug"])
    notes.sort(key=lambda n: n["published"], reverse=True)
    return notes


def render_card(n: dict) -> str:
    t = lambda s: html.escape(s, quote=False)
    a = lambda s: html.escape(s, quote=False).replace('"', "&quot;")
    return (
        f'        <a href="{a(n["file"])}" class="fn-card-link" data-categories="{a(" ".join(n["categories"]))}">\n'
        f'          <section class="section-block" style="--accent: {n["accent"]}">\n'
        f'            <i class="fas fa-arrow-right fn-card-icon"></i>\n'
        f'            <h2>{t(n["title"])}</h2>\n'
        f'            <p>{t(n["summary"])}</p>\n'
        f'          </section>\n'
        f'        </a>\n'
    )


def main() -> None:
    check = "--check" in sys.argv
    index_html = INDEX.read_text(encoding="utf-8")
    if index_html.count(START) != 1 or index_html.count(END) != 1:
        fail(["field-notes/index.html must contain exactly one FN-CARDS:START and one FN-CARDS:END marker"])

    notes = read_articles(valid_categories(index_html))
    cards = "".join(render_card(n) for n in notes)
    before, rest = index_html.split(START, 1)
    _, after = rest.split(END, 1)
    new_index = f"{before}{START}\n{cards}        {END}{after}"
    new_manifest = json.dumps({"count": len(notes), "notes": notes}, indent=2, ensure_ascii=False) + "\n"

    old_manifest = MANIFEST.read_text(encoding="utf-8") if MANIFEST.exists() else ""
    changed = new_index != index_html or new_manifest != old_manifest

    if check:
        if changed:
            print("generate_field_notes: index or manifest is out of date - run python scripts/generate_field_notes.py", file=sys.stderr)
            sys.exit(1)
        print(f"generate_field_notes: up to date ({len(notes)} notes)")
        return

    if changed:
        INDEX.write_text(new_index, encoding="utf-8")
        MANIFEST.write_text(new_manifest, encoding="utf-8")
        print(f"generate_field_notes: wrote {len(notes)} cards and field-notes.json")
    else:
        print(f"generate_field_notes: no changes ({len(notes)} notes)")


if __name__ == "__main__":
    main()
